<template>
  <div
    class="flex flex-col items-center justify-center fixed top-0 left-0 right-0 bottom-0 h-screen w-full bg-white z-10"
  >
    <div class="loadingio-spinner-dual-ring-rg6hta6k54">
      <div class="ldio-ntkz1zwo32o">
        <div></div>
        <div><div></div></div>
      </div>
    </div>
    <p class="font-bold text-xl">Cargando</p>
  </div>
</template>

<script>
export default {
  name: "Loader",
};
</script>

<style scoped>
@keyframes ldio-ntkz1zwo32o {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-ntkz1zwo32o div {
  box-sizing: border-box !important;
}
.ldio-ntkz1zwo32o > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #15803d transparent #15803d transparent;
  animation: ldio-ntkz1zwo32o 1s linear infinite;
}
.ldio-ntkz1zwo32o > div:nth-child(2) {
  border-color: transparent;
}
.ldio-ntkz1zwo32o > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-ntkz1zwo32o > div:nth-child(2) div:before,
.ldio-ntkz1zwo32o > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #15803d;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #15803d;
}
.ldio-ntkz1zwo32o > div:nth-child(2) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #15803d;
}
.loadingio-spinner-dual-ring-rg6hta6k54 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-ntkz1zwo32o {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ntkz1zwo32o div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
